0.0.2

diff --git a/Matsya-K8s-MultiNode-HostSyncTemplate b/Matsya-K8s-MultiNode-HostSyncTemplate
--- a/Matsya-K8s-MultiNode-HostSyncTemplate
+++ b/Matsya-K8s-MultiNode-HostSyncTemplate
@@ -1,5 +1,7 @@
 #!/bin/bash
 
+set -e
+
 clear
 
 RED='\033[0;31m'
@@ -15,12 +17,13 @@ BOLD=$(tput bold)
 NORM=$(tput sgr0)
 ORANGE='\033[1;33m'
 
-BASE="BASENAMETOBEUSED"
-CLUSTERNAME="CLUSTERNAMETOBEUSED"
-THEOSNAME="OSNAMETOBEUSED"
-THEREQUIREDUSER="THENAMEOFTHEUSER"
-ELIGIBLEUSERS="USERSELIGIBLE"
+BASE="/opt/Matsya"
+CLUSTERNAME="Alpha7"
+THEOSNAME="POSB"
+THEREQUIREDUSER="mxHju2Ks6nxa81S"
+ELIGIBLEUSERS="prathamos├mxHju2Ks6nxa81S"
 CURRENTUSER=$(whoami)
+THEHOMEREQUIREDFORUSER="$BASE/K8sMN/$CLUSTERNAME/$THEREQUIREDUSER"
 
 IFS='├' read -r -a ALLOWEDUSERS <<< $ELIGIBLEUSERS
 EITHERTHIS="${ALLOWEDUSERS[0]}"
@@ -33,85 +36,282 @@ else
 	exit
 fi
 
-COUNTER=1
-ACTUALNORMAL=()
-CHOICENAME=""
-SLNO=0
-INCREMENT=1
+DoubleQuotes='"'
+NoQuotes=''
 
 echo -e "${ORANGE}==============================================================================${NC}"
 echo -e "${BLUE}${BOLD}\x1b[4mM${NORM}${NC}ultifaceted deploy${BLUE}${BOLD}\x1b[4mA${NORM}${NC}gnostic ${BLUE}${BOLD}\x1b[4mT${NORM}${NC}imesaving ${BLUE}${BOLD}\x1b[4mS${NORM}${NC}calable anal${BLUE}${BOLD}\x1b[4mY${NORM}${NC}tics ${BLUE}${BOLD}\x1b[4mA${NORM}${NC}malgamated ${BOLD}\x1b[30;44mPLATFORM\x1b[m${NORM}"
 echo -e "${GREEN}==============================================================================${NC}"
 echo ''
-echo -e "\x1b[3m\x1b[4mK8s MULTINODE (SYNC)\x1b[m"
+echo -e "\x1b[3m\x1b[4mK8s MULTINODE (SYNC) [$CLUSTERNAME]\x1b[m"
 echo ''
-echo -e "${PURPLE}-------------------------${NC}"
-echo -e "${GREEN}${BOLD}TERMINALS AVAILABLE [$CLUSTERNAME]${NORM}${NC}"
-echo -e "${PURPLE}-------------------------${NC}"
+read -p "Enter File Path For Settings > " -e -i "/opt/Matsya/Repo/Sync" NODES_JSON
+echo "                                                                         "
 
-COUNTERe=1
-while read Terminal; do
+if [ -f "$NODES_JSON" ]
+then
+	ABC="XYZ"
+else
+	exit
+fi
+
+TerminalsCount=$(jq '.K8sMN.Cluster.Terminals | length' $NODES_JSON)
+TerminalsCount=$((TerminalsCount - 1))
+FINAL_BEFORE_CONNECT_TERMINAL_LIST=()
+FINAL_TERMINAL_LIST=()
+GLOBALSSHPORT=$(jq '.K8sMN.Cluster.Terminal[0].SSHPort' $NODES_JSON)
+GLOBALSSHPORT="${GLOBALSSHPORT//$DoubleQuotes/$NoQuotes}"
+GLOBALUSERNAME=$(jq '.K8sMN.Cluster.Terminal[0].UserName' $NODES_JSON)
+GLOBALUSERNAME="${GLOBALUSERNAME//$DoubleQuotes/$NoQuotes}"
+	
+for((j=0;j<$TerminalsCount;j++))
+do
+	Terminal=$(jq '.K8sMN.Cluster.Terminals['${j}'].HostName' $NODES_JSON)
+	Terminal="${Terminal//$DoubleQuotes/$NoQuotes}"
+	TerminalIP=$(jq '.K8sMN.Cluster.Terminals['${j}'].IPAddress' $NODES_JSON)
+	TerminalIP="${TerminalIP//$DoubleQuotes/$NoQuotes}"
+	TerminalSSHPort=""
+	TerminalTheRqLocation=""
+	TerminalUserName=""
+	TerminalTheRqBase=""	
+	CHECKIFTOOMIT=$(jq '.K8sMN.Cluster.Terminals['${j}'].OMIT?' $NODES_JSON)
+	CHECKIFTOOMIT="${CHECKIFTOOMIT//$DoubleQuotes/$NoQuotes}"
+	if [ "$CHECKIFTOOMIT" == "null" ] || [ "$CHECKIFTOOMIT" == "" ] ; then
+		CHECKIFUSERNAMEMISSING=$(jq '.K8sMN.Cluster.Terminals['${j}'].UserName?' $NODES_JSON)
+		CHECKIFUSERNAMEMISSING="${CHECKIFUSERNAMEMISSING//$DoubleQuotes/$NoQuotes}"
+		if [ "$CHECKIFUSERNAMEMISSING" == "null" ] || [ "$CHECKIFUSERNAMEMISSING" = "" ] ; then
+			if [ "$GLOBALUSERNAME" == "" ] || [ "$GLOBALUSERNAME" == "" ] ; then			
+				echo '-----------------------'					
+				echo -e "${RED}${BOLD}\x1b[5mERROR !!! > ${NORM}${NC}\x1b[3mProperty 'UserName' Missing In '$NODES_JSON' For Terminal => $Terminal ($TerminalIP)"
+				echo '-----------------------'
+				echo ''
+				exit
+			else
+				TerminalUserName="$GLOBALUSERNAME"
+			fi
+		else
+			TerminalUserName="$CHECKIFUSERNAMEMISSING"				
+		fi
+										
+		CHECKIFSSHPORTMISSING=$(jq '.K8sMN.Cluster.Terminals['${j}'].SSHPort?' $NODES_JSON)
+		CHECKIFSSHPORTMISSING="${CHECKIFSSHPORTMISSING//$DoubleQuotes/$NoQuotes}"
+		if [ "$CHECKIFSSHPORTMISSING" == "null" ] || [ "$CHECKIFSSHPORTMISSING" = "" ] ; then
+			if [ "$GLOBALSSHPORT" == "" ] || [ "$GLOBALSSHPORT" == "" ] ; then			
+				echo '-----------------------'					
+				echo -e "${RED}${BOLD}\x1b[5mERROR !!! > ${NORM}${NC}\x1b[3mProperty 'SSHPort' Missing In '$NODES_JSON' For Terminal => $Terminal ($TerminalIP)"
+				echo '-----------------------'
+				echo ''
+				exit
+			else
+				TerminalSSHPort="$GLOBALSSHPORT"
+			fi
+		else
+			TerminalSSHPort="$CHECKIFSSHPORTMISSING"							
+		fi
+
+		CHECKIFBASELOCATIONMISSING=$(jq '.K8sMN.Cluster.Terminals['${j}'].BaseLocation?' $NODES_JSON)
+		CHECKIFBASELOCATIONMISSING="${CHECKIFBASELOCATIONMISSING//$DoubleQuotes/$NoQuotes}"
+		if [ "$CHECKIFBASELOCATIONMISSING" == "null" ] || [ "$CHECKIFBASELOCATIONMISSING" = "" ] ; then
+			if [ "$BASE" == "" ] || [ "$BASE" == "" ] ; then			
+				echo '-----------------------'					
+				echo -e "${RED}${BOLD}\x1b[5mERROR !!! > ${NORM}${NC}\x1b[3mProperty 'BaseLocation' Missing In '$NODES_JSON' For Terminal => $Terminal ($TerminalIP)"
+				echo '-----------------------'
+				echo ''
+				exit
+			else
+				TerminalTheRqBase="$BASE"
+			fi
+		else
+			TerminalTheRqBase="$CHECKIFBASELOCATIONMISSING"							
+		fi
+									
+		CHECKIFTHELOCATIONMISSING=$(jq '.K8sMN.Cluster.Terminals['${j}'].LAN?' $NODES_JSON)
+		CHECKIFTHELOCATIONMISSING="${CHECKIFTHELOCATIONMISSING//$DoubleQuotes/$NoQuotes}"
+		if [ "$CHECKIFTHELOCATIONMISSING" == "null" ] || [ "$CHECKIFTHELOCATIONMISSING" = "" ] ; then
+			TerminalTheRqLocation="PUBLIC"
+		else
+			TerminalTheRqLocation="$CHECKIFTHELOCATIONMISSING"							
+		fi			
+		
+		FINAL_BEFORE_CONNECT_TERMINAL_LIST+=("$Terminal├$TerminalIP├$TerminalTheRqLocation├$TerminalSSHPort├$TerminalUserName├$TerminalTheRqBase")																			
+	fi
+done
+	
+sudo rm -rf /home/$CURRENTUSER/.ssh/known_hosts
+echo '-----------------------'
+RANDOMFOLDERNAME=$(cat /dev/urandom | tr -dc 'a-zA-Z0-9' | fold -w 15 | head -n 1)
+sudo mkdir -p $BASE/K8sMN/$RANDOMFOLDERNAME
+sudo chmod -R 777 $BASE/K8sMN/$RANDOMFOLDERNAME
+pushd $BASE/K8sMN/$RANDOMFOLDERNAME
+touch $RANDOMFOLDERNAME
+for Terminal in "${FINAL_BEFORE_CONNECT_TERMINAL_LIST[@]}"
+do
 	IFS='├' read -r -a TerminalVals <<< $Terminal
+	THEREQUIREDPORT="${TerminalVals[3]}"
 	THEREQUIREDIP="${TerminalVals[1]}"
 	THEREQUIREDHOSTNAME="${TerminalVals[0]}"
-	THEREQUIREDLAN="${TerminalVals[2]}"
-	if [ $THEOSNAME == "AWS" ] || [ $THEOSNAME == "GCP" ] || [ $THEOSNAME == "AZR" ] || [ $THEOSNAME == "CLD" ] || [ $THEOSNAME == "E2E7" ] || [ $THEOSNAME == "E2E8" ] ; then
-		if [ $THEREQUIREDLAN == "PUBLIC" ] || [ $THEOSNAME == "PUBLIC" ] ; then			
-			echo "($COUNTERe) $THEREQUIREDHOSTNAME / $THEREQUIREDIP"
-			COUNTERe=$((COUNTERe + 1))
-			ACTUALNORMAL=("${ACTUALNORMAL[@]}" "$COUNTER~$Terminal")
-			COUNTER=$((COUNTER + 1))
-		fi
-	else
-		echo "($COUNTERe) $THEREQUIREDHOSTNAME / $THEREQUIREDIP"
+	if [ "$THEREQUIREDIP" == "null" ] || [ "$THEREQUIREDIP" = "" ] ; then
+		THEREQUIREDIP=$THEREQUIREDHOSTNAME
+	fi		
+	(
+	set -Ee
+	function _catch {
+		echo "ERROR"
+		exit 0
+	}
+	function _finally {
+		abc=xyz
+	}
+	trap _catch ERR
+	trap _finally EXIT
+	THERESPONSE=$(ssh $THEREQUIREDUSER@$THEREQUIREDIP -p $THEREQUIREDPORT -o ConnectTimeout=15 -o "StrictHostKeyChecking=no" -i "$BASE/matsya-k8s-mn-$CLUSTERNAME-terminal.pem" "echo \"$RANDOMFOLDERNAME\"")
+	echo "$Terminal├$THERESPONSE" >> $RANDOMFOLDERNAME		
+	)		
+done	
+popd
+echo '-----------------------'	
+echo ''
+	
+COUNTERf=1
+ERROR_TERMINAL_LIST=()
+while read LINE; do
+	IFS='├' read -r -a TerminalFullVals <<< $LINE
+	ACCESSTRYRESULT="${TerminalFullVals[6]}"
+	if [ "$ACCESSTRYRESULT" == "$RANDOMFOLDERNAME" ] || [ "$ACCESSTRYRESULT" == "$RANDOMFOLDERNAME" ] ; then
+		ACTUALNORMAL=("${ACTUALNORMAL[@]}" "$COUNTER~$LINE")
+		COUNTER=$((COUNTER + 1))
 		COUNTERe=$((COUNTERe + 1))
-		ACTUALNORMAL=("${ACTUALNORMAL[@]}" "$COUNTER~$Terminal")
-		COUNTER=$((COUNTER + 1))	
+		FINAL_TERMINAL_LIST+=("$LINE")
+	else
+		COUNTERf=$((COUNTERf + 1))
+		ERROR_TERMINAL_LIST+=("$LINE")	
 	fi
-done < $BASE/K8sMN/$CLUSTERNAME/HOSTS
+done < $BASE/K8sMN/$RANDOMFOLDERNAME/$RANDOMFOLDERNAME	
+sudo rm -rf $BASE/K8sMN/$RANDOMFOLDERNAME
+
+sleep 2
+clear
+
+echo -e "${ORANGE}==============================================================================${NC}"
+echo -e "${BLUE}${BOLD}\x1b[4mM${NORM}${NC}ultifaceted deploy${BLUE}${BOLD}\x1b[4mA${NORM}${NC}gnostic ${BLUE}${BOLD}\x1b[4mT${NORM}${NC}imesaving ${BLUE}${BOLD}\x1b[4mS${NORM}${NC}calable anal${BLUE}${BOLD}\x1b[4mY${NORM}${NC}tics ${BLUE}${BOLD}\x1b[4mA${NORM}${NC}malgamated ${BOLD}\x1b[30;44mPLATFORM\x1b[m${NORM}"
+echo -e "${GREEN}==============================================================================${NC}"
+echo ''
+echo -e "\x1b[3m\x1b[4mK8s MULTINODE (SYNC) [$CLUSTERNAME]\x1b[m"
+echo ''
+echo -e "${PURPLE}-------------------------${NC}"
+echo -e "${GREEN}${BOLD}TERMINALS AVAILABLE${NORM}${NC}"
+echo -e "${PURPLE}-------------------------${NC}"
+
 if [ "$COUNTERe" -lt "2" ]; then
 	echo -e "${RED}${BOLD}xxxxx${NORM}${NC}"
 	echo -e "${PURPLE}-------------------------${NC}"
 	echo ''
 	exit
-fi
+fi	
+	
+COUNTERe=1
+for Terminal in "${FINAL_TERMINAL_LIST[@]}"
+do
+	IFS='├' read -r -a TerminalVals <<< $Terminal
+	THEREQUIREDIP="${TerminalVals[1]}"
+	THEREQUIREDHOSTNAME="${TerminalVals[0]}"
+	THEREQUIREDPORT="${TerminalVals[3]}"
+	if [ "$THEREQUIREDIP" == "null" ] || [ "$THEREQUIREDIP" = "" ] ; then
+		THEREQUIREDIP=""
+	else
+		THEREQUIREDIP=" ($THEREQUIREDIP)"
+	fi				
+	echo "($COUNTERe) $THEREQUIREDHOSTNAME ($THEREQUIREDPORT)$THEREQUIREDIP"
+	COUNTERe=$((COUNTERe + 1)) 
+done
 echo -e "${PURPLE}-------------------------${NC}"
 echo ''
-read -p "Enter Terminal Number To Connect > " -e -i "0" NodeNumber
-IFS=',' read -r -a CHOICELIST <<< $NodeNumber
-for _CHOICE in "${CHOICELIST[@]}"
-do
-	if ! [[ "$_CHOICE" =~ ^[0-9]+$ ]] ; 
-	 then exec >&2; echo ""; echo -e "${RED}Number Required!!${NC}"; echo ""; exit;
-	fi
-	if [ $_CHOICE == "0" ] ; then
-		echo ""; echo -e "${RED}Number Required!!${NC}"; echo ""; exit;	
-	fi		
-done
-for _CHOICE in "${CHOICELIST[@]}"
-do
-	for _ACTUALNORMAL in "${ACTUALNORMAL[@]}"
+
+if [ "$COUNTERf" -lt "2" ]; then
+	ABC="XYZ"
+else
+	echo -e "${PURPLE}-------------------------${NC}"
+	echo -e "${RED}${BOLD}TERMINALS DOWN${NORM}${NC}"
+	echo -e "${PURPLE}-------------------------${NC}"
+	for Terminal in "${ERROR_TERMINAL_LIST[@]}"
 	do
-		IFS='~' read -r -a _ACTUALNORMALSPLIT <<< $_ACTUALNORMAL
-		if [ "$_CHOICE" == "${_ACTUALNORMALSPLIT[0]}" ] || [ "$_CHOICE" == "${_ACTUALNORMALSPLIT[0]}" ] ; then	
-			SLNO="$(($SLNO+$INCREMENT))"
-			CHOICENAME="$CHOICENAME,${_ACTUALNORMALSPLIT[1]}"
-		fi	
-	done				
-done
-if [ "$SLNO" -lt "1" ]; then
-    echo ""; echo -e "${RED}Valid Number Required!!${NC}"; echo ""; exit;
+		IFS='├' read -r -a TerminalVals <<< $Terminal
+		THEREQUIREDIP="${TerminalVals[1]}"
+		THEREQUIREDHOSTNAME="${TerminalVals[0]}"
+		THEREQUIREDPORT="${TerminalVals[3]}"
+		if [ "$THEREQUIREDIP" == "null" ] || [ "$THEREQUIREDIP" = "" ] ; then
+			THEREQUIREDIP=""
+		else
+			THEREQUIREDIP=" ($THEREQUIREDIP)"
+		fi				
+		echo -e "${RED}\x1b[3m* $THEREQUIREDHOSTNAME ($THEREQUIREDPORT)$THEREQUIREDIP${NC}"
+	done	
+	echo -e "${PURPLE}-------------------------${NC}"
+	echo ''	
 fi
-echo "${CHOICELIST[@]}"
+	
+NodeNumber="-1"
+if [ "$#" -ne 1 ]; then
+	read -p "Enter Terminal Number(s) To Sync (0 For All) > " -e -i "-1" NodeNumber
+	echo ''
+else
+	NodeNumber="0"
+fi	
+#HOSTS /etc/hosts .Sync	 /home/$CURRENTUSER/.ssh/known_hosts
+sudo rm -rf $BASE/K8sMN/$CLUSTERNAME/HOSTS
+sudo rm -rf $BASE/K8sMN/$CLUSTERNAME/ListOfHosts
+sudo touch $BASE/K8sMN/$CLUSTERNAME/HOSTS
+sudo touch $BASE/K8sMN/$CLUSTERNAME/ListOfHosts
+echo '#!/bin/bash
+' | sudo tee -a $BASE/K8sMN/$CLUSTERNAME/ListOfHosts > /dev/null
+sudo chmod 777 $BASE/K8sMN/$CLUSTERNAME/HOSTS
+		
+for Terminal in "${FINAL_TERMINAL_LIST[@]}"
+do
+	IFS='├' read -r -a TerminalVals <<< $Terminal
+	THEREQUIREDIP="${TerminalVals[1]}"
+	THEREQUIREDHOSTNAME="${TerminalVals[0]}"
+	THEREQUIREDLANTYPE="${TerminalVals[2]}"
+	THEREQUIREDCONNECTPORT="${TerminalVals[3]}"
+	echo "$THEREQUIREDHOSTNAME├$THEREQUIREDIP├$THEREQUIREDLANTYPE├$THEREQUIREDCONNECTPORT" | sudo tee -a $BASE/K8sMN/$CLUSTERNAME/HOSTS > /dev/null
+	if [ "$THEREQUIREDIP" == "null" ] || [ "$THEREQUIREDIP" = "" ] ; then
+		ABC="XYZ"
+	else
+		echo "sudo sed -i -e s~\"$THEREQUIREDIP\"~\"#$THEREQUIREDIP\"~g /etc/hosts > /dev/null" | sudo tee -a $BASE/K8sMN/$CLUSTERNAME/ListOfHosts > /dev/null
+		echo "echo '$THEREQUIREDIP	$THEREQUIREDHOSTNAME' | sudo tee -a /etc/hosts > /dev/null" | sudo tee -a $BASE/K8sMN/$CLUSTERNAME/ListOfHosts > /dev/null
+	fi											 
+done
 
+for Terminal in "${FINAL_TERMINAL_LIST[@]}"
+do
+	IFS='├' read -r -a TerminalVals <<< $Terminal
+	THEREQUIREDIP="${TerminalVals[1]}"
+	THEREQUIREDHOSTNAME="${TerminalVals[0]}"
+	THEREQUIREDCONNECTPORT="${TerminalVals[3]}"
+	THEORIGINALUSERHERE="${TerminalVals[4]}"
+	THEORIGINALBASEHERE="${TerminalVals[5]}"	
+	echo "$THEREQUIREDHOSTNAME├$THEREQUIREDIP├$THEREQUIREDLANTYPE├$THEREQUIREDCONNECTPORT" | sudo tee -a $BASE/K8sMN/$CLUSTERNAME/HOSTS > /dev/null
+	if [ "$THEREQUIREDIP" == "null" ] || [ "$THEREQUIREDIP" = "" ] ; then
+		THEREQUIREDIP=$THEREQUIREDHOSTNAME
+	fi
+	scp -P $THEREQUIREDCONNECTPORT -o "StrictHostKeyChecking=no" -i "$BASE/matsya-k8s-mn-$CLUSTERNAME-terminal.pem" $BASE/K8sMN/$CLUSTERNAME/HOSTS $THEREQUIREDUSER@$THEREQUIREDIP:$THEORIGINALBASEHERE/K8sMN/$CLUSTERNAME/$THEREQUIREDUSER
+	ssh -p $THEREQUIREDCONNECTPORT -o "StrictHostKeyChecking=no" -i "$BASE/matsya-k8s-mn-$CLUSTERNAME-terminal.pem" $THEREQUIREDUSER@$THEREQUIREDIP "sudo rm -rf /home/$THEORIGINALUSERHERE/.ssh/known_hosts && sudo rm -rf $THEORIGINALBASEHERE/K8sMN/$CLUSTERNAME/$THEREQUIREDUSER/.ssh/known_hosts && sudo rm -rf $THEORIGINALBASEHERE/K8sMN/$CLUSTERNAME/HOSTS"	
+done
+	
+sudo chown root:root $BASE/K8sMN/$CLUSTERNAME/HOSTS
+sudo chmod u=r,g=,o= $BASE/K8sMN/$CLUSTERNAME/HOSTS
 
-
-
-
-
-
-
-
+	
+	
+	
+	
+	
+	
+	
+	
+	
+	
+	
 
 
 
